"""Add preferred_timezone to User model

Revision ID: 0d633dc35d14
Revises: 14913f8dcb00
Create Date: 2024-11-27 00:14:43.372558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d633dc35d14'
down_revision = '14913f8dcb00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_timezone', sa.String(length=50), server_default='UTC', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferred_timezone')

    # ### end Alembic commands ###
