"""prepare for git

Revision ID: 252aa1dda2c3
Revises: 43b48f64d10b
Create Date: 2024-11-28 00:32:45.106386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252aa1dda2c3'
down_revision = '43b48f64d10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
