"""Add tz_name to Event table

Revision ID: a970536d6c08
Revises: 252aa1dda2c3
Create Date: 2024-11-28 09:17:48.154213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a970536d6c08'
down_revision = '252aa1dda2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tz_name', sa.String(length=50), server_default='UTC', nullable=False))
        batch_op.add_column(sa.Column('dont_send_confirmation', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_rating', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('total_voters', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('total_voters')
        batch_op.drop_column('total_rating')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('dont_send_confirmation')
        batch_op.drop_column('tz_name')

    # ### end Alembic commands ###
